sudo: true

language: java

jdk: oraclejdk8

before_install:
  - sudo apt-get -qq update
  - >
     sudo apt-get install -y
     bzip2
     gzip
     hunspell
     hunspell-de-de
     procps
     sox
     tar
     tesseract-ocr
     tesseract-ocr-deu
     unzip
  - wget https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-64bit-static.tar.xz
  - tar xf ffmpeg-release-64bit-static.tar.xz
  - sudo mv ffmpeg-*/ff* /usr/bin/
  - wget https://netix.dl.sourceforge.net/project/synfig/releases/1.0.2/linux/synfigstudio_1.0.2_amd64.deb
  - sudo dpkg -i synfigstudio_1.0.2_amd64.deb

install:
  - wget https://raw.githubusercontent.com/lkiesow/opencast/f/mh-12718-animate-travis-test/modules/animate-impl/src/test/resources/synfig-test-animation.sif
  - synfig -t ffmpeg -i synfig-test-animation.sif -o out.mkv

script:
  - mvn --batch-mode clean install -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Pnone
