name: Test LTI Tools

on:
  - pull_request

jobs:
  main:
    runs-on: ubuntu-20.04
    env:
      BASE_REF: origin/${{ github.event.pull_request.base.ref }}
    steps:
      - name: install tools
        run: |
          sudo apt update -q
          sudo apt install -qqy patchutils curl

      - name: check diff for docs changes
        id: check-changes
        run: |
          if [ -n "$(curl -s -L https://github.com/lkiesow/opencast/pull/15.patch | lsdiff --include='?/docs/*')" ]
          then
          echo 'Write-Output "::set-output name=changed::true"'
          fi

      - run: echo ${{ steps.check-changes.output.changed }}

      - run: echo ${{ steps.check-changes.output }}

      - name: Only if docs changes
        if: ${{ steps.check-changes.output.changed == 'true' }}
        run: |
          echo Docs have changed. Do something!
