name: Test Opencast

on:
  - push
  - pull_request

jobs:
  documentation:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: set up python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: install dependencies
      run: |
        pip install -q mkdocs markdown_inline_graphviz_extension mkdocs-windmill
        cd docs/guides
        npm ci

    - name: check documentation
      run: bash ./.style-and-markdown-build.sh

  database:
    strategy:
      matrix:
        db:
          - 'mysql:8'
          - 'mariadb:10'
    runs-on: ubuntu-latest
    container: ubuntu
    services:
      mydb:
        image: ${{ matrix.db }}
        env:
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
    steps:
    - name: initialize database
      run: |
        apt update -q
        apt install -q -y mysql-client
        mysql --host mydb -uroot -ppassword -e 'select version()'
        mysql --host mydb -uroot -ppassword -e 'create database opencast'

    - name: check upgrade path
      run: bash ./docs/upgrade/.test.sh
