name: Test LTI Tools

on:
  - pull_request

jobs:
  main:
    runs-on: ubuntu-20.04
    env:
      BASE_REF: origin/${{ github.event.pull_request.base.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - run: git diff --name-only --diff-filter=AM ${{ github.event.before }} ${{ github.sha }}

      - run: git remote -v

      - run: git fetch origin

      - name: git log
        run: git log --oneline "${BASE_REF}..HEAD"

      - name: git diff
        run: git diff --name-only "${BASE_REF}...HEAD"
